from views.home import Home
from views.test import Test
from views.search import Search, search_data
from views.request import Request_Add, Request, request_data, Request_Finger, Waiting, Request_Check
from views.admin import System_Management, User_Management, Product_Management, User_Id, user_data, User_Name, User_Lname, User_Department, User_Permission, User_Lockeraccess, User_Finger, User_Result, User_Edit, Item_Number, product_data, Product_Name, Part_Number, Part_Name, Drawing_Number, Product_Locker, Quantity, Other, Product_Result, Product_Section, Product_Qrcode, Locker_Control, locker_data, Locker_Control2, Locker_Management, Buzzer_Setting, Product_Edit, Admin_Finger, admin_data, Inventory_Edit

__all__ = [ 'Home',
            'Request',
            'Request_Add',
            'Test',
            'Search',
            'System_Management',
            'User_Management',
            'Product_Management',
            'request_data',
            'User_Id',
            'user_data',
            'User_Name',
            'User_Lname',
            'User_Department',
            'User_Permission',
            'User_Lockeraccess',
            'User_Finger',
            'User_Result',
            'Item_Number',
            'product_data',
            'Product_Name',
            'Part_Number',
            'Part_Name',
            'Drawing_Number',
            'Product_Locker',
            'Quantity',
            'Other',
            'Product_Result',
            'Product_Section',
            'Product_Qrcode',
            'Locker_Control',
            'locker_data',
            'Locker_Control2',
            'Locker_Management',
            'Buzzer_Setting',
            'Product_Edit',
            'User_Edit',
            'Admin_Finger',
            'admin_data',
            'Request_Finger',
            'Waiting',
            'Request_Check',
            'Inventory_Edit',
            'search_data']